language: java
sudo: false
install: true
addons:
  sonarcloud: 
    organization: riis-ci-github
    token: 7bd278ca15577d17248a163146b7686f6c1e7c27
jdk:
  - oraclejdk8
script:
  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
